<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>1stepshop.in Site Map - Generated by www.xml-sitemaps.com</title>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
    <style type="text/css">
        body {
            background-color: #fff;
            font-family: "Roboto", "Helvetica", "Arial", sans-serif;
            margin: 0;
        }

        #top {

            background-color: #b1d1e8;
            font-size: 16px;
            padding-bottom: 40px;
        }



        h3 {
            margin: auto;
            padding: 10px;
            max-width: 600px;
            color: #666;
        }

        h3 span {
            float: right;
        }

        h3 a {
            font-weight: normal;
            display: block;
        }


        #cont {
            position: relative;
            border-radius: 6px;
            box-shadow: 0 16px 24px 2px rgba(0, 0, 0, 0.14), 0 6px 30px 5px rgba(0, 0, 0, 0.12), 0 8px 10px -5px rgba(0, 0, 0, 0.2);

            background: #f3f3f3;

            margin: -20px 30px 0px 30px;
            padding: 20px;
        }

        a:link,
        a:visited {
            color: #0180AF;
            text-decoration: underline;
        }

        a:hover {
            color: #666;
        }


        #footer {
            padding: 10px;
            text-align: center;
        }

        ul {
            margin: 0px;

            padding: 0px;
            list-style: none;
        }
        li {
            margin: 0px;
        }
        li ul {
            margin-left: 20px;
        }

        .lhead {
            background: #ddd;
            padding: 10px;
            margin: 10px 0px;
        }

        .lcount {
            padding: 0px 10px;
        }

        .lpage {
            border-bottom: #ddd 1px solid;
            padding: 5px;
        }
        .last-page {
            border: none;
        }
    </style>
</head>

<body>


<div class="single-page main-grid-border" >


<div id="cont">
    <ul class="level-0">



                        <li class="lhead">Home Page </li>

                        <li class="lpage"><a href="https://www.1stepshop.in/" title="1StepShop">1StepShop</a></li>
                        <li class="lhead">Login/Register </li>

                        <li class="lpage"><a href="https://www.1stepshop.in/login" title="Login">Login</a></li>
                        <li class="lpage"><a href="https://www.1stepshop.in/register" title="Register">Register</a></li>
                        <li class="lhead">Ad Posting </li>

                        <li class="lpage"><a href="https://www.1stepshop.in/adPost" title="Post an Ad">Post an Ad</a></li>
                        <li class="lhead">Ad Category  </li>

                        <li class="lpage"><a href="https://www.1stepshop.in/categories?categoryId=1" title="Mobiles">Mobiles</a></li>
                        <li class="lpage"><a href="https://www.1stepshop.in/categories?categoryId=2" title="Electronics and Appliances">Electronics and Appliances</a></li>
                        <li class="lpage"><a href="https://www.1stepshop.in/categories?categoryId=3" title="Automobiles">Automobiles</a></li>
                        <li class="lpage"><a href="https://www.1stepshop.in/categories?categoryId=4" title="Furnitures">Furnitures</a></li>
                        <li class="lpage"><a href="https://www.1stepshop.in/categories?categoryId=5" title="Books, Sports and Hobbies">Books, Sports and Hobbies</a></li>
                        <li class="lpage"><a href="https://www.1stepshop.in/categories?categoryId=7" title="Pets">Pets</a></li>
                        <li class="lpage"><a href="https://www.1stepshop.in/categories?categoryId=6" title="Fashion">Fashion</a></li>
                        <li class="lpage"><a href="https://www.1stepshop.in/categories?categoryId=8" title="Real Estate">Real Estate</a></li>
                        <li class="lpage"><a href="https://www.1stepshop.in/categories?categoryId=11" title="Shopping and Showroom">Shopping and Showroom</a></li>
                        <li class="lpage"><a href="https://www.1stepshop.in/categories?categoryId=9" title="Jobs and Services">Jobs and Services</a></li>
                        <li class="lpage"><a href="https://www.1stepshop.in/categories?categoryId=10" title="Tution and Training">Tution and Training</a></li>
                        <li class="lpage"><a href="https://www.1stepshop.in/categories?categoryId=12" title="Health, Fitness and Beauty">Health, Fitness and Beauty</a></li>
                        <li class="lhead">Contact us  </li>

                        <li class="lpage"><a href="https://www.1stepshop.in/contactUs" title="Contact Us">Contact Us</a></li>
                        <li class="lhead">Terms </li>

                        <li class="lpage"><a href="https://www.1stepshop.in/terms" title="Terms">Terms</a></li>
                        <li class="lpage"><a href="https://www.1stepshop.in/privacy" title="Privacy">Privacy</a></li>
                    </ul>
    
</div></div></div>
</body>

</html>